version: '3'

services:
  contas_pagar:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: contas_pagar
    image: mespindula/contas-pagar
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/financeiro
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8080:8080'

  db:
    image: postgres
    container_name: db_postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=financeiro
    ports:
      - "5432:5432"